---
- name: check if /usr/local/bin/oc exists
  stat:
    path: /usr/local/bin/oc
  register: oc_client_cmd
  tags: [ setup, tools, client, ignitions ]

- name: check if /usr/local/bin/openshift-install exists
  stat:
    path: /usr/local/bin/openshift-install
  register: openshift_install_cmd
  tags: [ setup, tools, client, ignitions ]

- name: check for the version of oc client
  command: /usr/local/bin/oc version | grep "{{ ocp4_version }}"
  register: oc_client_version
  changed_when: false
  tags: [ setup, tools, client, ignitions ]
  ignore_errors: yes

- name: Set tools are missing variable
  vars:
    current_version: "Client Version: {{ ocp4_version }}"
  set_fact:
    tools_missing: true
  tags: [ setup, tools, client, ignitions ]
  when: not oc_client_cmd.stat.exists or not oc_client_cmd.stat.exists

- name: Check if OpenShift Versions match
  vars:
    current_version: "Client Version: {{ ocp4_version }}"
  set_fact:
    oc_version_match: "{{ true if oc_client_version.stdout == current_version else false }}"
  tags: [ setup, tools, client, ignitions ]
  when:  oc_client_cmd.stat.exists and oc_client_cmd.stat.exists

- name: check if the oc client tool version is matches {{ ocp4_version }}
  set_fact:
    download_tools: "{{ true if tools_missing or not oc_version_match else false }}"
  tags: [ setup, tools, client, ignitions ]

- name: Download OpenShift 4 client
  get_url:
    url: "{{ ocp4_release_url }}/{{ ocp4_client }}"
    dest: "/tmp/{{ ocp4_client }}"
  register: dl_ocp4_client
  when: download_tools
  tags: [ setup, tools, client ]

- name: Download OpenShift 4 installer
  get_url:
    url: "{{ ocp4_release_url }}/{{ ocp4_installer }}"
    dest: "/tmp/{{ ocp4_installer }}"
  register: dl_ocp4_installer
  when: download_tools
  tags: [ setup, tools, installer, ignitions ]

- name: Extract ocp client into /usr/local/bin/oc
  unarchive:
    src: "/tmp/{{ ocp4_client }}"
    dest: /usr/local/bin
  register: extract_ocp_client
  when: download_tools
  tags: [ setup, tools, client ]

- name: Extract openshift-install into /usr/local/bin/
  unarchive:
    src:  "/tmp/{{ ocp4_installer }}"
    dest:  /usr/local/bin
  register: extract_ocp_installer
  when: download_tools
  tags: [ setup, tools, installer, ignitions ]

- name: Remove openshift client tar file
  file:
    path: "/tmp/{{ ocp4_client }}"
    state: absent
  when: extract_ocp_client.changed
  tags: [ setup, tools, client ]

- name: Remove openshift installer  tar file
  file:
    path: "/tmp/{{ ocp4_installer }}"
    state: absent
  when: extract_ocp_installer.changed
  tags: [ setup , tools, installer]
